# <font color='red'><b>Bootstrap assignment</b> </font>

<b>There will be some functions that start with the word "grader" ex: grader_sampples(), grader_30().. etc, you should not change those function definition.

Every Grader function has to return True.</b>

<font color='blue'> <b>Importing packages</b> </font>

In [1]:
import numpy as np # importing numpy for numerical computation
from sklearn.datasets import load_boston # here we are using sklearn's boston dataset
from sklearn.metrics import mean_squared_error # importing mean_squared_error metric
import warnings 

warnings.filterwarnings("ignore") 

In [2]:
boston = load_boston()
x=boston.data #independent variables
y=boston.target #target variable

In [3]:
x.shape

(506, 13)

In [4]:
x[:5]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00]])

## <font color='red'><b>Task 1</b></font>

<font color='red'> <b>Step - 1</b></font>

*  <font color='blue'><b>Creating samples</b></font><br>
    <b> Randomly create 30 samples from the whole boston data points</b>
    *  Creating each sample: Consider any random 303(60% of 506) data points from whole data set and then replicate any 203 points from the sampled points
    
     For better understanding of this procedure lets check this examples, assume we have 10 data points [1,2,3,4,5,6,7,8,9,10], first we take 6 data points randomly , consider we have selected [4, 5, 7, 8, 9, 3] now we will replicate 4 points from [4, 5, 7, 8, 9, 3], consder they are [5, 8, 3,7] so our final sample will be [4, 5, 7, 8, 9, 3, 5, 8, 3,7]
* <font color='blue'><b> Create 30 samples </b></font>
    *  Note that as a part of the Bagging when you are taking the random samples <b>make sure each of the sample will have different set of columns</b><br>
Ex: Assume we have 10 columns[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10] for the first sample we will select [3, 4, 5, 9, 1, 2] and for the second sample  [7, 9, 1, 4, 5, 6, 2] and so on...
Make sure each sample will have atleast 3 feautres/columns/attributes

<font color='red'><b>Step - 2 </b></font>

<font color='blue'><b>Building High Variance Models on each of the sample and finding train MSE value</b></font>

*  Build a regression trees on each of 30 samples.
*  Computed the predicted values of each data point(506 data points) in your corpus.
*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{30}\sum_{k=1}^{30}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$
*  Now calculate the $MSE =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$

<font color='red'> <b>Step - 3 </b></font>

*  <font color='blue'><b>Calculating the OOB score </b></font>

*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{k}\sum_{\text{k= model which was buit on samples not included } x^{i}}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$.
*  Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

# <font color='red'><b>Task 2</b></font>

*  <font color='blue'><b>Computing CI of OOB Score and Train MSE</b></font>
  *   Repeat Task 1 for 35 times, and for each iteration store the Train MSE and OOB score </li>
<li> After this we will have 35 Train MSE values and 35 OOB scores </li>
<li> using these 35 values (assume like a sample) find the confidence intravels of MSE and OOB Score </li>
<li> you need to report CI of MSE and CI of OOB Score </li>
<li> Note: Refer the Central_Limit_theorem.ipynb to check how to find the confidence intravel</li>
</ol>

# <font color='red'><b>Task 3</b></font>

*  <font color='blue'><b>Given a single query point predict the price of house.</b></font>

Consider xq= [0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60] 
Predict the house price for this point as mentioned in the step 2 of Task 1.

<br><br><br>

# <font color='blue'> <b>Task - 1</b></font>

<font color='blue'><b>Step - 1</b></font>

*  <font color='blue'> <b>Creating samples</b></font>

<font color='Orange'><b>Algorithm</b></font>

![alt text](https://i.imgur.com/BTVYXQ1.jpg/)

*  <font color='blue'><b> Write code for generating samples</b></font>

In [5]:
from scipy.sparse import vstack
def generating_samples(input_data, target_data):

    '''In this function, we will write code for generating 30 samples '''
    # you can use random.choice to generate random indices without replacement
    # Please have a look at this link https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.choice.html for more details
    # Please follow above pseudo code for generating samples 
    

    # return sampled_input_data , sampled_target_data,selected_rows,selected_columns
    #note please return as lists
    
    
    selecting_rows=np.random.choice(x.shape[0],303,replace=False)
    replicaing_rows=np.random.choice(selecting_rows.shape[0],203,replace=False)
    selecting_columns=np.random.randint(3,13,3)
    sample_data=x[selecting_rows[:,None],selecting_columns]
    target_of_sample_data=y[selecting_rows]
    replicated_sample_data=sample_data[replicaing_rows]
    target_of_replicated_sample_data=y[replicaing_rows]
    final_sample_data=np.vstack((sample_data,replicated_sample_data))
    final_target_data=np.vstack((target_of_sample_data.reshape(-1,1),target_of_replicated_sample_data.reshape(-1,1)))
    return final_sample_data,final_target_data,selecting_rows,selecting_columns


In [6]:
#print(x.shape[1])
#selecting_columns=np.random.choice(x.shape[1],3,replace=True)

In [7]:

a,b,c,d=generating_samples(x,y)
print(len(a))
print(len( b))
print(len(c))
print(len(d))
print(type(a))

506
506
303
3
<class 'numpy.ndarray'>


In [8]:
#print(d)

In [9]:
for i in range(4):
    a=np.random.randint(3,13,3)
    print(a)
    

[3 3 3]
[6 4 3]
[ 6 11  8]
[4 8 3]


<font color='cyan'> <b> Grader function - 1 </b> </fongt>

In [12]:
def grader_samples(a,b,c,d):
    length = (len(a)==506  and len(b)==506)
    sampled = (len(a)-len(set([str(i) for i in a]))==203)
    rows_length = (len(c)==303)
    column_length= (len(d)>=3)
    assert(length and sampled and rows_length and column_length)
    return True
a,b,c,d = generating_samples(x, y)
grader_samples(a,b,c,d)

True

*  <font color='blue'> <b>Create 30 samples </b>

![alt text](https://i.imgur.com/p8eZaWL.jpg)

In [13]:
# Use generating_samples function to create 30 samples 
# store these created samples in a list
list_input_data =[]
list_output_data =[]
list_selected_row= []
list_selected_columns=[]
for i in range(0,30):
    a,b,c,d=generating_samples(x,y)
    list_input_data.append(a)
    list_output_data.append(b)
    list_selected_row.append(c)
    list_selected_columns.append(d)

<font color='cyan'> <b>Grader function - 2 </b></font>

In [14]:
def grader_30(a):
    assert(len(a)==30 and len(a[0])==506)
    return True
grader_30(list_input_data)

True

<br>

<font color='red'><b>Step - 2 </b></font>

<font color='orange'><b>Flowchart for building tree</b></font>

![alt text](https://i.imgur.com/pcXfSmp.png)

### training the models

In [15]:
from sklearn.tree import DecisionTreeRegressor
l=[]
for i  in range(30):
    model=0
    input_data=list_input_data[i]
    target_data=list_output_data[i]
    model=DecisionTreeRegressor(max_depth=None)
    model.fit(input_data,target_data)
    l.append(model)
print(len(l))
    

30


In [16]:
ypred=[]
for i in range(len(x)):
    dp=x[i]
    l1=[]
    for j in range(30):
        yp=0
        column_sampling=dp[list_selected_columns[j]]
        yp=l[j].predict(column_sampling.reshape(1,-1))
        l1.append(yp)
    l1=np.array(l1)
    l1=np.median(l1)
    ypred.append(l1)
print(len(ypred))

506


*  <font color='blue'><b> Write code for building regression trees</b></font>

## MSE

In [17]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y,ypred)


18.872800970811884

<font color='orange'><b>Flowchart for calculating MSE </b></font>

![alt text](https://i.imgur.com/sPEE618.png)

After getting predicted_y for each data point, we can use sklearns mean_squared_error to calculate the MSE between predicted_y and actual_y.

*  <font color='blue'><b> Write code for calculating MSE</b></font>

<font color='blue'><b>Step - 3 </b></font>

<font color='orange'><b>Flowchart for calculating OOB score</b></font>

![alt text](https://i.imgur.com/95S5Mtm.png)

Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

*  <font color='blue'><b> Write code for calculating OOB score </b></font>

In [18]:
ypd=[]
for i in range(len(x)):
    l2=[]
    dp=x[i]
    for j in range(30):
        yp=0
        if dp!=list_input_data[j]:
            column_sampling=dp[list_selected_columns[j]]
            yp=l[j].predict(column_sampling.reshape(1,-1))
            l2.append(yp)
    l2=np.array(l2)
    l2=np.median(l2)
    ypd.append(l2)
print(len(ypd))

506


In [19]:
a=0
for i in range(len(y)):
    a=a+(y[i]-ypd[i])**2
a=a/(len(y))
print("OOB:",a)
    

OOB: 18.872800970811888


# <font color='blue'><b>Task 2</b></font>

In [23]:
from scipy.sparse import vstack
def generating_sample(input_data, target_data):

    '''In this function, we will write code for generating 30 samples '''
    # you can use random.choice to generate random indices without replacement
    # Please have a look at this link https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.choice.html for more details
    # Please follow above pseudo code for generating samples 
    

    # return sampled_input_data , sampled_target_data,selected_rows,selected_columns
    #note please return as lists
    
    
    selecting_rows=np.random.choice(x.shape[0],303,replace=False)
    replicaing_rows=np.random.choice(selecting_rows.shape[0],203,replace=False)
    selecting_columns=np.random.randint(3,13,3)
    sample_data=x[selecting_rows[:,None],selecting_columns]
    target_of_sample_data=y[selecting_rows]
    replicated_sample_data=sample_data[replicaing_rows]
    target_of_replicated_sample_data=y[replicaing_rows]
    final_sample_data=np.vstack((sample_data,replicated_sample_data))
    final_target_data=np.vstack((target_of_sample_data.reshape(-1,1),target_of_replicated_sample_data.reshape(-1,1)))
    return final_sample_data,final_target_data,selecting_rows,selecting_columns


In [20]:
def appending(x,y):
    list_input_data =[]
    list_output_data =[]
    list_selected_row= []
    list_selected_columns=[]
    for i in range(0,30):
        a,b,c,d=generating_samples(x,y)
        list_input_data.append(a)
        list_output_data.append(b)
        list_selected_row.append(c)
        list_selected_columns.append(d)
    return list_input_data,list_output_data,list_selected_row,list_selected_columns

In [21]:
def splitting_30_MSE_OOB(list_input_data,list_output_data):
    l=[]
    for i  in range(30):
        model=0
        input_data=list_input_data[i]
        target_data=list_output_data[i]
        model=DecisionTreeRegressor(max_depth=None)
        model.fit(input_data,target_data)
        l.append(model)
    #calculating mse
    ypred=[]
    for i in range(len(x)):
        dp=x[i]
        l1=[]
        for j in range(30):
            yp=0
            column_sampling=dp[list_selected_columns[j]]
            yp=l[j].predict(column_sampling.reshape(1,-1))
            l1.append(yp)
        l1=np.array(l1)
        l1=np.median(l1)
        ypred.append(l1)
    M=mean_squared_error(y,ypred)
    #calculating oob
    ypd=[]
    for i in range(len(x)):
        l2=[]
        dp=x[i]
        for j in range(30):
            yp=0
            if dp!=list_input_data[j]:
                column_sampling=dp[list_selected_columns[j]]
                yp=l[j].predict(column_sampling.reshape(1,-1))
                l2.append(yp)
        l2=np.array(l2)
        l2=np.median(l2)
        ypd.append(l2)
    #print(len(ypd))
    a=0
    for i in range(len(y)):
        a=a+(y[i]-ypd[i])**2
    a=a/(len(y))
    return M,a

In [24]:
mse=[]
oob=[]
for i in range(35):
    generating_sample(x,y)
    l1,l2,s1,s2=appending(x,y)
    p,q=splitting_30_MSE_OOB(l1,l2)
    mse.append(p)
    oob.append(q)

In [25]:
print(mse)
print(oob)

[77.15671693017126, 86.34723074647441, 89.08639224772624, 109.92465413900152, 73.65962606262657, 90.22779546125504, 68.93934287193291, 87.1507026906597, 85.15883185050994, 77.54521007406586, 77.98816309989995, 83.45040019762845, 92.67104643719807, 92.3432129762297, 80.68233572134386, 76.45327692687745, 85.52533366887599, 71.75075082729305, 78.90643142292491, 85.7785807806324, 86.52094487401187, 76.99208034832016, 81.1958975883152, 77.77978553599158, 75.04423112871109, 85.89350419960473, 67.78825591475366, 77.69157118343368, 80.831656386937, 88.78005226346345, 77.58341930781243, 87.30327596166936, 75.1573233695652, 82.92821351633759, 83.74451937508005]
[77.1567169301713, 86.3472307464744, 89.08639224772624, 109.92465413900146, 73.65962606262666, 90.22779546125501, 68.93934287193294, 87.15070269065973, 85.15883185050996, 77.54521007406588, 77.9881630999, 83.45040019762845, 92.67104643719806, 92.34321297622971, 80.68233572134383, 76.4532769268775, 85.525333668876, 71.75075082729305, 78.90

### confidence intervals

In [27]:
import scipy.stats
def confidence_interval(data, confidence=0.9):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.std(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h

In [28]:
confidence_interval(mse)

(7.823320489610473, 5.554627045384372, 10.092013933836574)

In [29]:
confidence_interval(oob)

(7.823320489610455, 5.554627045384359, 10.09201393383655)

# <font color='blue'><b>Task 3</b></font>

<font color='orange'><b>Flowchart for Task 3</b></font>

<b>Hint: </b> We created 30 models by using 30 samples in TASK-1. Here, we need send query point "xq"  to 30 models and perform the regression on the output generated by 30 models.

![alt text](https://i.imgur.com/Y5cNhQk.png)

In [30]:
# Use generating_samples function to create 30 samples 
# store these created samples in a list
list_input_data =[]
list_output_data =[]
list_selected_row= []
list_selected_columns=[]
for i in range(0,30):
    a,b,c,d=generating_samples(x,y)
    list_input_data.append(a)
    list_output_data.append(b)
    list_selected_row.append(c)
    list_selected_columns.append(d)

In [31]:
from sklearn.tree import DecisionTreeRegressor
l=[]
for i  in range(30):
    model=0
    input_data=list_input_data[i]
    target_data=list_output_data[i]
    model=DecisionTreeRegressor(max_depth=None)
    model.fit(input_data,target_data)
    l.append(model)
print(len(l))

30


*  <font color='blue'><b> Write code for TASK 3 </b></font>

In [32]:
xq= [0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60]
xq=np.array(xq)
for i in range(1):
    yprice=[]
    d=xq
    for j in range(30):
        yp=0
        column_sampling=dp[list_selected_columns[j]]
        yp=l[j].predict(column_sampling.reshape(1,-1))
        yprice.append(yp)
    yprice=np.array(yprice)
    yprice=np.mean(yprice)
print(yprice)
        

18.973382275132273


<br><br><br>

<font color='red'><b>Write observations for task 1, task 2, task 3 indetail</b></font>